run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - gosec
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  gosec:
    excludes:
      - G304  # file path from variable — acceptable in config loader
  goimports:
    local-prefixes: github.com/ondrejsindelka/praetor-server

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
