package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// InvestigationsPostgres implements storage.InvestigationRepo using pgxpool.
type InvestigationsPostgres struct {
	pool *pgxpool.Pool
}

// NewInvestigationsPostgres creates an InvestigationsPostgres backed by pool.
func NewInvestigationsPostgres(pool *pgxpool.Pool) *InvestigationsPostgres {
	return &InvestigationsPostgres{pool: pool}
}

const investigationSelectCols = `
	id, fleet_id, rule_id, playbook_id, trigger_type, triggered_at,
	host_ids, trigger_data, snapshot, llm_analysis, llm_metadata,
	status, error, completed_at, created_at`

// Create inserts a new investigation. The ID is generated by the database.
func (inv *InvestigationsPostgres) Create(ctx context.Context, i *storage.Investigation) error {
	triggerJSON, err := marshalNullableJSON(i.TriggerData)
	if err != nil {
		return fmt.Errorf("investigations: marshal trigger_data: %w", err)
	}
	snapshotJSON, err := marshalNullableJSON(i.Snapshot)
	if err != nil {
		return fmt.Errorf("investigations: marshal snapshot: %w", err)
	}
	llmMetaJSON, err := marshalNullableJSON(i.LLMMetadata)
	if err != nil {
		return fmt.Errorf("investigations: marshal llm_metadata: %w", err)
	}

	hostIDs := uuidStringsToText(i.HostIDs)

	const q = `
		INSERT INTO watchdog_investigations
			(fleet_id, rule_id, playbook_id, trigger_type, triggered_at,
			 host_ids, trigger_data, snapshot, llm_analysis, llm_metadata, status)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
		RETURNING id, created_at`
	row := inv.pool.QueryRow(ctx, q,
		i.FleetID, i.RuleID, i.PlaybookID, i.TriggerType, i.TriggeredAt,
		hostIDs, triggerJSON, snapshotJSON, i.LLMAnalysis, llmMetaJSON, i.Status,
	)
	return row.Scan(&i.ID, &i.CreatedAt)
}

// Get returns an investigation by ID scoped to fleetID.
func (inv *InvestigationsPostgres) Get(ctx context.Context, id, fleetID string) (*storage.Investigation, error) {
	const q = `SELECT ` + investigationSelectCols + ` FROM watchdog_investigations WHERE id=$1 AND fleet_id=$2`
	row := inv.pool.QueryRow(ctx, q, id, fleetID)
	result, err := scanInvestigation(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("investigations: %w", pgx.ErrNoRows)
	}
	return result, err
}

// List returns investigations matching the provided options.
func (inv *InvestigationsPostgres) List(ctx context.Context, opts storage.InvestigationListOptions) ([]*storage.Investigation, error) {
	q := `SELECT ` + investigationSelectCols + ` FROM watchdog_investigations WHERE fleet_id=$1`
	args := []any{opts.FleetID}
	idx := 2

	if opts.Status != "" {
		q += fmt.Sprintf(" AND status=$%d", idx)
		args = append(args, opts.Status)
		idx++
	}
	if opts.RuleID != "" {
		q += fmt.Sprintf(" AND rule_id=$%d", idx)
		args = append(args, opts.RuleID)
		idx++
	}
	if opts.HostID != "" {
		q += fmt.Sprintf(" AND $%d::uuid = ANY(host_ids)", idx)
		args = append(args, opts.HostID)
		idx++
	}
	if opts.Since != nil {
		q += fmt.Sprintf(" AND triggered_at >= $%d", idx)
		args = append(args, opts.Since)
		idx++
	}
	if opts.Until != nil {
		q += fmt.Sprintf(" AND triggered_at <= $%d", idx)
		args = append(args, opts.Until)
		idx++
	}
	q += " ORDER BY triggered_at DESC"
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", idx)
		args = append(args, opts.Limit)
		idx++
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", idx)
		args = append(args, opts.Offset)
	}

	rows, err := inv.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("investigations: list: %w", err)
	}
	defer rows.Close()

	var results []*storage.Investigation
	for rows.Next() {
		i, err := scanInvestigation(rows)
		if err != nil {
			return nil, fmt.Errorf("investigations: scan: %w", err)
		}
		results = append(results, i)
	}
	return results, rows.Err()
}

// UpdateStatus sets the status (and optional error) on an investigation.
func (inv *InvestigationsPostgres) UpdateStatus(ctx context.Context, id, status string, errMsg *string) error {
	_, err := inv.pool.Exec(ctx,
		"UPDATE watchdog_investigations SET status=$2, error=$3 WHERE id=$1",
		id, status, errMsg,
	)
	if err != nil {
		return fmt.Errorf("investigations: update status: %w", err)
	}
	return nil
}

// UpdateSnapshot stores a snapshot JSON blob on an investigation.
func (inv *InvestigationsPostgres) UpdateSnapshot(ctx context.Context, id string, snapshot map[string]any) error {
	b, err := json.Marshal(snapshot)
	if err != nil {
		return fmt.Errorf("investigations: marshal snapshot: %w", err)
	}
	_, err = inv.pool.Exec(ctx,
		"UPDATE watchdog_investigations SET snapshot=$2 WHERE id=$1",
		id, json.RawMessage(b),
	)
	if err != nil {
		return fmt.Errorf("investigations: update snapshot: %w", err)
	}
	return nil
}

// UpdateLLMAnalysis stores the LLM analysis and metadata.
func (inv *InvestigationsPostgres) UpdateLLMAnalysis(ctx context.Context, id string, analysis string, metadata map[string]any) error {
	b, err := json.Marshal(metadata)
	if err != nil {
		return fmt.Errorf("investigations: marshal llm_metadata: %w", err)
	}
	_, err = inv.pool.Exec(ctx,
		"UPDATE watchdog_investigations SET llm_analysis=$2, llm_metadata=$3 WHERE id=$1",
		id, analysis, json.RawMessage(b),
	)
	if err != nil {
		return fmt.Errorf("investigations: update llm analysis: %w", err)
	}
	return nil
}

// Complete marks an investigation as completed with the given status and sets completed_at.
func (inv *InvestigationsPostgres) Complete(ctx context.Context, id string, status string) error {
	_, err := inv.pool.Exec(ctx,
		"UPDATE watchdog_investigations SET status=$2, completed_at=NOW() WHERE id=$1",
		id, status,
	)
	if err != nil {
		return fmt.Errorf("investigations: complete: %w", err)
	}
	return nil
}

func scanInvestigation(row pgx.Row) (*storage.Investigation, error) {
	var i storage.Investigation
	var triggerDataJSON, snapshotJSON, llmMetaJSON []byte
	var hostIDStrs []string

	err := row.Scan(
		&i.ID, &i.FleetID, &i.RuleID, &i.PlaybookID, &i.TriggerType, &i.TriggeredAt,
		&hostIDStrs, &triggerDataJSON, &snapshotJSON, &i.LLMAnalysis, &llmMetaJSON,
		&i.Status, &i.Error, &i.CompletedAt, &i.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	i.HostIDs = hostIDStrs
	if len(triggerDataJSON) > 0 {
		if err := json.Unmarshal(triggerDataJSON, &i.TriggerData); err != nil {
			return nil, fmt.Errorf("investigations: unmarshal trigger_data: %w", err)
		}
	}
	if len(snapshotJSON) > 0 {
		if err := json.Unmarshal(snapshotJSON, &i.Snapshot); err != nil {
			return nil, fmt.Errorf("investigations: unmarshal snapshot: %w", err)
		}
	}
	if len(llmMetaJSON) > 0 {
		if err := json.Unmarshal(llmMetaJSON, &i.LLMMetadata); err != nil {
			return nil, fmt.Errorf("investigations: unmarshal llm_metadata: %w", err)
		}
	}
	return &i, nil
}

// marshalNullableJSON returns nil for a nil map, otherwise marshals to JSON.
func marshalNullableJSON(m map[string]any) (json.RawMessage, error) {
	if m == nil {
		return nil, nil
	}
	b, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// uuidStringsToText converts []string to a []string for pgx UUID array scanning.
// pgx handles []string -> uuid[] scanning natively.
func uuidStringsToText(ids []string) []string {
	if ids == nil {
		return []string{}
	}
	return ids
}
