package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// LLMProvidersPostgres implements storage.LLMProviderRepo using pgxpool.
type LLMProvidersPostgres struct {
	pool *pgxpool.Pool
}

// NewLLMProvidersPostgres creates an LLMProvidersPostgres backed by pool.
func NewLLMProvidersPostgres(pool *pgxpool.Pool) *LLMProvidersPostgres {
	return &LLMProvidersPostgres{pool: pool}
}

const llmProviderCols = `id, fleet_id, name, provider, endpoint, api_key_enc, default_model, is_default, created_at`

// Create inserts a new LLM provider. The ID is generated by the database.
func (l *LLMProvidersPostgres) Create(ctx context.Context, p *storage.LLMProvider) error {
	const q = `
		INSERT INTO watchdog_llm_providers
			(fleet_id, name, provider, endpoint, api_key_enc, default_model, is_default)
		VALUES ($1,$2,$3,$4,$5,$6,$7)
		RETURNING id, created_at`
	row := l.pool.QueryRow(ctx, q,
		p.FleetID, p.Name, p.Provider, p.Endpoint, p.APIKeyEnc, p.DefaultModel, p.IsDefault,
	)
	return row.Scan(&p.ID, &p.CreatedAt)
}

// Get returns an LLM provider by ID scoped to fleetID.
func (l *LLMProvidersPostgres) Get(ctx context.Context, id, fleetID string) (*storage.LLMProvider, error) {
	const q = `SELECT ` + llmProviderCols + ` FROM watchdog_llm_providers WHERE id=$1 AND fleet_id=$2`
	row := l.pool.QueryRow(ctx, q, id, fleetID)
	p, err := scanLLMProvider(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("llm_providers: %w", pgx.ErrNoRows)
	}
	return p, err
}

// GetDefault returns the default LLM provider for a fleet.
func (l *LLMProvidersPostgres) GetDefault(ctx context.Context, fleetID string) (*storage.LLMProvider, error) {
	const q = `SELECT ` + llmProviderCols + ` FROM watchdog_llm_providers WHERE fleet_id=$1 AND is_default=TRUE`
	row := l.pool.QueryRow(ctx, q, fleetID)
	p, err := scanLLMProvider(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("llm_providers: %w", pgx.ErrNoRows)
	}
	return p, err
}

// List returns LLM providers for a fleet with optional pagination.
func (l *LLMProvidersPostgres) List(ctx context.Context, opts storage.ListOptions) ([]*storage.LLMProvider, error) {
	q := `SELECT ` + llmProviderCols + ` FROM watchdog_llm_providers WHERE fleet_id=$1 ORDER BY name`
	args := []any{opts.FleetID}
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", len(args)+1)
		args = append(args, opts.Limit)
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", len(args)+1)
		args = append(args, opts.Offset)
	}
	rows, err := l.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("llm_providers: list: %w", err)
	}
	defer rows.Close()

	var providers []*storage.LLMProvider
	for rows.Next() {
		p, err := scanLLMProvider(rows)
		if err != nil {
			return nil, fmt.Errorf("llm_providers: scan: %w", err)
		}
		providers = append(providers, p)
	}
	return providers, rows.Err()
}

// Update replaces mutable fields of an existing LLM provider.
func (l *LLMProvidersPostgres) Update(ctx context.Context, p *storage.LLMProvider) error {
	const q = `
		UPDATE watchdog_llm_providers
		SET name=$3, provider=$4, endpoint=$5, api_key_enc=$6, default_model=$7, is_default=$8
		WHERE id=$1 AND fleet_id=$2`
	tag, err := l.pool.Exec(ctx, q,
		p.ID, p.FleetID,
		p.Name, p.Provider, p.Endpoint, p.APIKeyEnc, p.DefaultModel, p.IsDefault,
	)
	if err != nil {
		return fmt.Errorf("llm_providers: update: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("llm_providers: update: %w", pgx.ErrNoRows)
	}
	return nil
}

// Delete removes an LLM provider scoped to fleetID.
func (l *LLMProvidersPostgres) Delete(ctx context.Context, id, fleetID string) error {
	_, err := l.pool.Exec(ctx,
		"DELETE FROM watchdog_llm_providers WHERE id=$1 AND fleet_id=$2", id, fleetID)
	if err != nil {
		return fmt.Errorf("llm_providers: delete: %w", err)
	}
	return nil
}

func scanLLMProvider(row pgx.Row) (*storage.LLMProvider, error) {
	var p storage.LLMProvider
	err := row.Scan(
		&p.ID, &p.FleetID, &p.Name, &p.Provider, &p.Endpoint,
		&p.APIKeyEnc, &p.DefaultModel, &p.IsDefault, &p.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &p, nil
}
