package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// PlaybooksPostgres implements storage.PlaybookRepo using pgxpool.
type PlaybooksPostgres struct {
	pool *pgxpool.Pool
}

// NewPlaybooksPostgres creates a PlaybooksPostgres backed by pool.
func NewPlaybooksPostgres(pool *pgxpool.Pool) *PlaybooksPostgres {
	return &PlaybooksPostgres{pool: pool}
}

// Create inserts a new playbook. The ID is generated by the database.
func (p *PlaybooksPostgres) Create(ctx context.Context, pb *storage.Playbook) error {
	stepsJSON, err := json.Marshal(pb.Steps)
	if err != nil {
		return fmt.Errorf("playbooks: marshal steps: %w", err)
	}
	var llmConfigJSON json.RawMessage
	if pb.LLMConfig != nil {
		b, err := json.Marshal(pb.LLMConfig)
		if err != nil {
			return fmt.Errorf("playbooks: marshal llm_config: %w", err)
		}
		llmConfigJSON = b
	}
	const q = `
		INSERT INTO watchdog_playbooks (fleet_id, name, description, steps, llm_prompt, llm_config)
		VALUES ($1,$2,$3,$4,$5,$6)
		RETURNING id, created_at, updated_at`
	row := p.pool.QueryRow(ctx, q,
		pb.FleetID, pb.Name, pb.Description,
		json.RawMessage(stepsJSON), pb.LLMPrompt, llmConfigJSON,
	)
	return row.Scan(&pb.ID, &pb.CreatedAt, &pb.UpdatedAt)
}

// Get returns a playbook by ID scoped to fleetID.
func (p *PlaybooksPostgres) Get(ctx context.Context, id, fleetID string) (*storage.Playbook, error) {
	const q = `
		SELECT id, fleet_id, name, description, steps, llm_prompt, llm_config, created_at, updated_at
		FROM watchdog_playbooks
		WHERE id=$1 AND fleet_id=$2`
	row := p.pool.QueryRow(ctx, q, id, fleetID)
	pb, err := scanPlaybook(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("playbooks: %w", pgx.ErrNoRows)
	}
	return pb, err
}

// List returns playbooks for a fleet with optional pagination.
func (p *PlaybooksPostgres) List(ctx context.Context, opts storage.ListOptions) ([]*storage.Playbook, error) {
	q := `
		SELECT id, fleet_id, name, description, steps, llm_prompt, llm_config, created_at, updated_at
		FROM watchdog_playbooks
		WHERE fleet_id=$1
		ORDER BY name`
	args := []any{opts.FleetID}
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", len(args)+1)
		args = append(args, opts.Limit)
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", len(args)+1)
		args = append(args, opts.Offset)
	}
	rows, err := p.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("playbooks: list: %w", err)
	}
	defer rows.Close()

	var pbs []*storage.Playbook
	for rows.Next() {
		pb, err := scanPlaybook(rows)
		if err != nil {
			return nil, fmt.Errorf("playbooks: scan: %w", err)
		}
		pbs = append(pbs, pb)
	}
	return pbs, rows.Err()
}

// Update replaces mutable fields of an existing playbook.
func (p *PlaybooksPostgres) Update(ctx context.Context, pb *storage.Playbook) error {
	stepsJSON, err := json.Marshal(pb.Steps)
	if err != nil {
		return fmt.Errorf("playbooks: marshal steps: %w", err)
	}
	var llmConfigJSON json.RawMessage
	if pb.LLMConfig != nil {
		b, err := json.Marshal(pb.LLMConfig)
		if err != nil {
			return fmt.Errorf("playbooks: marshal llm_config: %w", err)
		}
		llmConfigJSON = b
	}
	const q = `
		UPDATE watchdog_playbooks
		SET name=$3, description=$4, steps=$5, llm_prompt=$6, llm_config=$7, updated_at=NOW()
		WHERE id=$1 AND fleet_id=$2
		RETURNING updated_at`
	row := p.pool.QueryRow(ctx, q,
		pb.ID, pb.FleetID,
		pb.Name, pb.Description,
		json.RawMessage(stepsJSON), pb.LLMPrompt, llmConfigJSON,
	)
	err = row.Scan(&pb.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("playbooks: update: %w", pgx.ErrNoRows)
	}
	return err
}

// Delete removes a playbook scoped to fleetID.
func (p *PlaybooksPostgres) Delete(ctx context.Context, id, fleetID string) error {
	_, err := p.pool.Exec(ctx,
		"DELETE FROM watchdog_playbooks WHERE id=$1 AND fleet_id=$2", id, fleetID)
	if err != nil {
		return fmt.Errorf("playbooks: delete: %w", err)
	}
	return nil
}

func scanPlaybook(row pgx.Row) (*storage.Playbook, error) {
	var pb storage.Playbook
	var stepsJSON, llmConfigJSON []byte
	err := row.Scan(
		&pb.ID, &pb.FleetID, &pb.Name, &pb.Description,
		&stepsJSON, &pb.LLMPrompt, &llmConfigJSON,
		&pb.CreatedAt, &pb.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	if len(stepsJSON) > 0 {
		if err := json.Unmarshal(stepsJSON, &pb.Steps); err != nil {
			return nil, fmt.Errorf("playbooks: unmarshal steps: %w", err)
		}
	}
	if len(llmConfigJSON) > 0 {
		if err := json.Unmarshal(llmConfigJSON, &pb.LLMConfig); err != nil {
			return nil, fmt.Errorf("playbooks: unmarshal llm_config: %w", err)
		}
	}
	return &pb, nil
}
