// Package postgres provides pgx/v5-backed implementations of the watchdog storage interfaces.
package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// RulesPostgres implements storage.RuleRepo using pgxpool.
type RulesPostgres struct {
	pool *pgxpool.Pool
}

// NewRulesPostgres creates a RulesPostgres backed by pool.
func NewRulesPostgres(pool *pgxpool.Pool) *RulesPostgres {
	return &RulesPostgres{pool: pool}
}

// Create inserts a new rule. The ID is generated by the database.
func (r *RulesPostgres) Create(ctx context.Context, rule *storage.Rule) error {
	selectorJSON, err := json.Marshal(rule.HostSelector)
	if err != nil {
		return fmt.Errorf("rules: marshal host_selector: %w", err)
	}
	conditionJSON, err := json.Marshal(rule.Condition)
	if err != nil {
		return fmt.Errorf("rules: marshal condition: %w", err)
	}
	const q = `
		INSERT INTO watchdog_rules
			(fleet_id, name, description, enabled, host_selector, condition, playbook_id, cooldown_s, priority)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
		RETURNING id, created_at, updated_at`
	row := r.pool.QueryRow(ctx, q,
		rule.FleetID, rule.Name, rule.Description, rule.Enabled,
		json.RawMessage(selectorJSON), json.RawMessage(conditionJSON),
		rule.PlaybookID, rule.CooldownS, rule.Priority,
	)
	return row.Scan(&rule.ID, &rule.CreatedAt, &rule.UpdatedAt)
}

// Get returns a rule by ID scoped to fleetID.
func (r *RulesPostgres) Get(ctx context.Context, id, fleetID string) (*storage.Rule, error) {
	const q = `
		SELECT id, fleet_id, name, description, enabled, host_selector, condition,
		       playbook_id, cooldown_s, priority, created_at, updated_at
		FROM watchdog_rules
		WHERE id = $1 AND fleet_id = $2`
	row := r.pool.QueryRow(ctx, q, id, fleetID)
	rule, err := scanRule(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("rules: %w", pgx.ErrNoRows)
	}
	return rule, err
}

// List returns rules for a fleet with optional pagination.
func (r *RulesPostgres) List(ctx context.Context, opts storage.ListOptions) ([]*storage.Rule, error) {
	q := `
		SELECT id, fleet_id, name, description, enabled, host_selector, condition,
		       playbook_id, cooldown_s, priority, created_at, updated_at
		FROM watchdog_rules
		WHERE fleet_id = $1
		ORDER BY name`
	args := []any{opts.FleetID}
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", len(args)+1)
		args = append(args, opts.Limit)
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", len(args)+1)
		args = append(args, opts.Offset)
	}
	rows, err := r.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("rules: list: %w", err)
	}
	defer rows.Close()
	return collectRules(rows)
}

// ListEnabled returns all enabled rules for a fleet.
func (r *RulesPostgres) ListEnabled(ctx context.Context, fleetID string) ([]*storage.Rule, error) {
	const q = `
		SELECT id, fleet_id, name, description, enabled, host_selector, condition,
		       playbook_id, cooldown_s, priority, created_at, updated_at
		FROM watchdog_rules
		WHERE fleet_id = $1 AND enabled = TRUE
		ORDER BY name`
	rows, err := r.pool.Query(ctx, q, fleetID)
	if err != nil {
		return nil, fmt.Errorf("rules: list enabled: %w", err)
	}
	defer rows.Close()
	return collectRules(rows)
}

// Update replaces mutable fields of an existing rule.
func (r *RulesPostgres) Update(ctx context.Context, rule *storage.Rule) error {
	selectorJSON, err := json.Marshal(rule.HostSelector)
	if err != nil {
		return fmt.Errorf("rules: marshal host_selector: %w", err)
	}
	conditionJSON, err := json.Marshal(rule.Condition)
	if err != nil {
		return fmt.Errorf("rules: marshal condition: %w", err)
	}
	const q = `
		UPDATE watchdog_rules
		SET name=$3, description=$4, enabled=$5, host_selector=$6, condition=$7,
		    playbook_id=$8, cooldown_s=$9, priority=$10, updated_at=NOW()
		WHERE id=$1 AND fleet_id=$2
		RETURNING updated_at`
	row := r.pool.QueryRow(ctx, q,
		rule.ID, rule.FleetID,
		rule.Name, rule.Description, rule.Enabled,
		json.RawMessage(selectorJSON), json.RawMessage(conditionJSON),
		rule.PlaybookID, rule.CooldownS, rule.Priority,
	)
	err = row.Scan(&rule.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("rules: update: %w", pgx.ErrNoRows)
	}
	return err
}

// Delete removes a rule scoped to fleetID.
func (r *RulesPostgres) Delete(ctx context.Context, id, fleetID string) error {
	_, err := r.pool.Exec(ctx,
		"DELETE FROM watchdog_rules WHERE id=$1 AND fleet_id=$2", id, fleetID)
	if err != nil {
		return fmt.Errorf("rules: delete: %w", err)
	}
	return nil
}

func scanRule(row pgx.Row) (*storage.Rule, error) {
	var rule storage.Rule
	var selectorJSON, conditionJSON []byte
	err := row.Scan(
		&rule.ID, &rule.FleetID, &rule.Name, &rule.Description, &rule.Enabled,
		&selectorJSON, &conditionJSON,
		&rule.PlaybookID, &rule.CooldownS, &rule.Priority,
		&rule.CreatedAt, &rule.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	if len(selectorJSON) > 0 {
		if err := json.Unmarshal(selectorJSON, &rule.HostSelector); err != nil {
			return nil, fmt.Errorf("rules: unmarshal host_selector: %w", err)
		}
	}
	if len(conditionJSON) > 0 {
		if err := json.Unmarshal(conditionJSON, &rule.Condition); err != nil {
			return nil, fmt.Errorf("rules: unmarshal condition: %w", err)
		}
	}
	return &rule, nil
}

func collectRules(rows pgx.Rows) ([]*storage.Rule, error) {
	var rules []*storage.Rule
	for rows.Next() {
		rule, err := scanRule(rows)
		if err != nil {
			return nil, fmt.Errorf("rules: scan: %w", err)
		}
		rules = append(rules, rule)
	}
	return rules, rows.Err()
}
