package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// SchedulesPostgres implements storage.ScheduleRepo using pgxpool.
type SchedulesPostgres struct {
	pool *pgxpool.Pool
}

// NewSchedulesPostgres creates a SchedulesPostgres backed by pool.
func NewSchedulesPostgres(pool *pgxpool.Pool) *SchedulesPostgres {
	return &SchedulesPostgres{pool: pool}
}

const scheduleCols = `id, fleet_id, name, cron_expr, playbook_id, host_ids, enabled, last_run_at, created_at`

// Create inserts a new schedule. The ID is generated by the database.
func (s *SchedulesPostgres) Create(ctx context.Context, sched *storage.Schedule) error {
	hostIDs := uuidStringsToText(sched.HostIDs)
	const q = `
		INSERT INTO watchdog_schedules (fleet_id, name, cron_expr, playbook_id, host_ids, enabled)
		VALUES ($1,$2,$3,$4,$5,$6)
		RETURNING id, created_at`
	row := s.pool.QueryRow(ctx, q,
		sched.FleetID, sched.Name, sched.CronExpr, sched.PlaybookID, hostIDs, sched.Enabled,
	)
	return row.Scan(&sched.ID, &sched.CreatedAt)
}

// Get returns a schedule by ID scoped to fleetID.
func (s *SchedulesPostgres) Get(ctx context.Context, id, fleetID string) (*storage.Schedule, error) {
	const q = `SELECT ` + scheduleCols + ` FROM watchdog_schedules WHERE id=$1 AND fleet_id=$2`
	row := s.pool.QueryRow(ctx, q, id, fleetID)
	sched, err := scanSchedule(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("schedules: %w", pgx.ErrNoRows)
	}
	return sched, err
}

// List returns schedules for a fleet with optional pagination.
func (s *SchedulesPostgres) List(ctx context.Context, opts storage.ListOptions) ([]*storage.Schedule, error) {
	q := `SELECT ` + scheduleCols + ` FROM watchdog_schedules WHERE fleet_id=$1 ORDER BY name`
	args := []any{opts.FleetID}
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", len(args)+1)
		args = append(args, opts.Limit)
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", len(args)+1)
		args = append(args, opts.Offset)
	}
	rows, err := s.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("schedules: list: %w", err)
	}
	defer rows.Close()
	return collectSchedules(rows)
}

// ListEnabled returns all enabled schedules for a fleet.
func (s *SchedulesPostgres) ListEnabled(ctx context.Context, fleetID string) ([]*storage.Schedule, error) {
	const q = `SELECT ` + scheduleCols + ` FROM watchdog_schedules WHERE fleet_id=$1 AND enabled=TRUE ORDER BY name`
	rows, err := s.pool.Query(ctx, q, fleetID)
	if err != nil {
		return nil, fmt.Errorf("schedules: list enabled: %w", err)
	}
	defer rows.Close()
	return collectSchedules(rows)
}

// Update replaces mutable fields of an existing schedule.
func (s *SchedulesPostgres) Update(ctx context.Context, sched *storage.Schedule) error {
	hostIDs := uuidStringsToText(sched.HostIDs)
	const q = `
		UPDATE watchdog_schedules
		SET name=$3, cron_expr=$4, playbook_id=$5, host_ids=$6, enabled=$7
		WHERE id=$1 AND fleet_id=$2`
	tag, err := s.pool.Exec(ctx, q,
		sched.ID, sched.FleetID,
		sched.Name, sched.CronExpr, sched.PlaybookID, hostIDs, sched.Enabled,
	)
	if err != nil {
		return fmt.Errorf("schedules: update: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("schedules: update: %w", pgx.ErrNoRows)
	}
	return nil
}

// Delete removes a schedule scoped to fleetID.
func (s *SchedulesPostgres) Delete(ctx context.Context, id, fleetID string) error {
	_, err := s.pool.Exec(ctx,
		"DELETE FROM watchdog_schedules WHERE id=$1 AND fleet_id=$2", id, fleetID)
	if err != nil {
		return fmt.Errorf("schedules: delete: %w", err)
	}
	return nil
}

// UpdateLastRunAt sets the last_run_at timestamp for a schedule.
func (s *SchedulesPostgres) UpdateLastRunAt(ctx context.Context, id string, t time.Time) error {
	_, err := s.pool.Exec(ctx,
		"UPDATE watchdog_schedules SET last_run_at=$2 WHERE id=$1", id, t)
	if err != nil {
		return fmt.Errorf("schedules: update last_run_at: %w", err)
	}
	return nil
}

func scanSchedule(row pgx.Row) (*storage.Schedule, error) {
	var sched storage.Schedule
	var hostIDStrs []string
	err := row.Scan(
		&sched.ID, &sched.FleetID, &sched.Name, &sched.CronExpr,
		&sched.PlaybookID, &hostIDStrs, &sched.Enabled, &sched.LastRunAt, &sched.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	sched.HostIDs = hostIDStrs
	return &sched, nil
}

func collectSchedules(rows pgx.Rows) ([]*storage.Schedule, error) {
	var scheds []*storage.Schedule
	for rows.Next() {
		sched, err := scanSchedule(rows)
		if err != nil {
			return nil, fmt.Errorf("schedules: scan: %w", err)
		}
		scheds = append(scheds, sched)
	}
	return scheds, rows.Err()
}
