package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ondrejsindelka/praetor-server/internal/watchdog/storage"
)

// WebhooksPostgres implements storage.WebhookRepo using pgxpool.
type WebhooksPostgres struct {
	pool *pgxpool.Pool
}

// NewWebhooksPostgres creates a WebhooksPostgres backed by pool.
func NewWebhooksPostgres(pool *pgxpool.Pool) *WebhooksPostgres {
	return &WebhooksPostgres{pool: pool}
}

const webhookCols = `id, fleet_id, name, url, events, secret_enc, enabled, created_at`

// Create inserts a new webhook. The ID is generated by the database.
func (w *WebhooksPostgres) Create(ctx context.Context, wh *storage.Webhook) error {
	const q = `
		INSERT INTO watchdog_webhooks (fleet_id, name, url, events, secret_enc, enabled)
		VALUES ($1,$2,$3,$4,$5,$6)
		RETURNING id, created_at`
	row := w.pool.QueryRow(ctx, q,
		wh.FleetID, wh.Name, wh.URL, wh.Events, wh.SecretEnc, wh.Enabled,
	)
	return row.Scan(&wh.ID, &wh.CreatedAt)
}

// Get returns a webhook by ID scoped to fleetID.
func (w *WebhooksPostgres) Get(ctx context.Context, id, fleetID string) (*storage.Webhook, error) {
	const q = `SELECT ` + webhookCols + ` FROM watchdog_webhooks WHERE id=$1 AND fleet_id=$2`
	row := w.pool.QueryRow(ctx, q, id, fleetID)
	wh, err := scanWebhook(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("webhooks: %w", pgx.ErrNoRows)
	}
	return wh, err
}

// List returns webhooks for a fleet with optional pagination.
func (w *WebhooksPostgres) List(ctx context.Context, opts storage.ListOptions) ([]*storage.Webhook, error) {
	q := `SELECT ` + webhookCols + ` FROM watchdog_webhooks WHERE fleet_id=$1 ORDER BY name`
	args := []any{opts.FleetID}
	if opts.Limit > 0 {
		q += fmt.Sprintf(" LIMIT $%d", len(args)+1)
		args = append(args, opts.Limit)
	}
	if opts.Offset > 0 {
		q += fmt.Sprintf(" OFFSET $%d", len(args)+1)
		args = append(args, opts.Offset)
	}
	rows, err := w.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("webhooks: list: %w", err)
	}
	defer rows.Close()

	var webhooks []*storage.Webhook
	for rows.Next() {
		wh, err := scanWebhook(rows)
		if err != nil {
			return nil, fmt.Errorf("webhooks: scan: %w", err)
		}
		webhooks = append(webhooks, wh)
	}
	return webhooks, rows.Err()
}

// ListEnabled returns all enabled webhooks for a fleet.
func (w *WebhooksPostgres) ListEnabled(ctx context.Context, fleetID string) ([]*storage.Webhook, error) {
	const q = `SELECT ` + webhookCols + ` FROM watchdog_webhooks WHERE fleet_id=$1 AND enabled=TRUE ORDER BY name`
	rows, err := w.pool.Query(ctx, q, fleetID)
	if err != nil {
		return nil, fmt.Errorf("webhooks: list enabled: %w", err)
	}
	defer rows.Close()

	var webhooks []*storage.Webhook
	for rows.Next() {
		wh, err := scanWebhook(rows)
		if err != nil {
			return nil, fmt.Errorf("webhooks: scan enabled: %w", err)
		}
		webhooks = append(webhooks, wh)
	}
	return webhooks, rows.Err()
}

// Update replaces mutable fields of an existing webhook.
func (w *WebhooksPostgres) Update(ctx context.Context, wh *storage.Webhook) error {
	const q = `
		UPDATE watchdog_webhooks
		SET name=$3, url=$4, events=$5, secret_enc=$6, enabled=$7
		WHERE id=$1 AND fleet_id=$2`
	tag, err := w.pool.Exec(ctx, q,
		wh.ID, wh.FleetID,
		wh.Name, wh.URL, wh.Events, wh.SecretEnc, wh.Enabled,
	)
	if err != nil {
		return fmt.Errorf("webhooks: update: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("webhooks: update: %w", pgx.ErrNoRows)
	}
	return nil
}

// Delete removes a webhook scoped to fleetID.
func (w *WebhooksPostgres) Delete(ctx context.Context, id, fleetID string) error {
	_, err := w.pool.Exec(ctx,
		"DELETE FROM watchdog_webhooks WHERE id=$1 AND fleet_id=$2", id, fleetID)
	if err != nil {
		return fmt.Errorf("webhooks: delete: %w", err)
	}
	return nil
}

func scanWebhook(row pgx.Row) (*storage.Webhook, error) {
	var wh storage.Webhook
	err := row.Scan(
		&wh.ID, &wh.FleetID, &wh.Name, &wh.URL, &wh.Events, &wh.SecretEnc, &wh.Enabled, &wh.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &wh, nil
}
